const int CHARGE_CONTROLLER_CURRENT_SENSOR_ID = 1;
const int BATTERY_CURRENT_SENSOR_ID = 2;

const int USB1_CURRENT_SENSOR_ID = 3;
const int USB2_CURRENT_SENSOR_ID = 4;
const int USB3_CURRENT_SENSOR_ID = 5;
const int USB4_CURRENT_SENSOR_ID = 6;

const int TEMPERATURE_SENSOR_ID = 7;
